
[main]
log_level = "INFO"
secret_key = "kXDZ2/1C3mA313ZGfw9dOEVIV0oC0Hnoi44Y0VVwptN43aVEkIpj3QCQuCe3UpwR"
data_directory = "data"

[server]
host = "127.0.0.1"
port = 8000

[database]
source = "sqlite3:data/db.sqlite3"
